### ISSUE TITLE
Currently only one completion could be added per task !

### ISSUE THREAD

**Issue by fsalmasri** [heartexlabs/label-studio-converter#11]
Is it possible to have multiple instance conversion?

**Comment by makseq** [comment]
I've just tried to make multiple completions per one task and it works well. 
![image](https://user-images.githubusercontent.com/501780/91592088-a86eef80-e966-11ea-8e2d-f97646dd89c3.png)

Can you provide more details?

**Comment by makseq** [comment]
@fsalmasri What type of conversion do you use? JSON_MIN?

**Comment by fsalmasri** [comment]
I tried both PASCAL VOC and COCO

**Comment by niklub** [comment]
@fsalmasri If you're trying to export multiple completions per task, that's possible only with `JSON` format
