### ISSUE TITLE
Importing from YOLO ("label" to "labels")

### ISSUE THREAD

**Issue by TByte007** [heartexlabs/label-studio-converter#149]
When importing  from YOLO dataset the generated JSON have `"from_name": "label"` which leaves the bounding boxes without labels. If I replace all the ` "from_name": "label"` to `"from_name": "labels"` and it works. I have no idea why I just found out what is the difference from "updated" XML from inside Label Studio and the generated one by label-studio-converter.

PS: I just saw that it generates the XML with this line `<RectangleLabels name="labels" toName="image">` and for some reason in the YOLO importer the default value is like this:
```
def convert_yolo_to_ls(input_dir, out_file,
                       to_name='image', from_name='label', out_type="annotations",
                       image_root_url='/data/local-files/?d=', image_ext='.jpg'): 
```

**Comment by makseq** [comment]
Hm.. previously we had this PR from our contributor - https://github.com/heartexlabs/label-studio-converter/pull/130, so.. looks like  it's wrong :(

**Comment by makseq** [comment]
Thanks for pointing me to this problem, hope this commit (it's in the master branch now) will help:
https://github.com/heartexlabs/label-studio-converter/commit/d20143762823a878e87128392d48463936bde50f
