### ISSUE TITLE
Incorrect tokenization in CoNLL 2003 export

### ISSUE THREAD

**Issue by david-waterworth** [heartexlabs/label-studio-converter#15]
I'm evaluating a number of different annotation interfaces and am currently looking at label-studio.

I noticed when I exported as json and colnll2003 I got quite different results for the same string. The reason seems to be the tokenization. I'm trying to identify named entities from IoT device identification strings - the string usually have delimiters like - or . in place of space (or none at all). i.e.

AHU-G1-V-1-1-Ctrl-Md

I tagged AHU-G1-V-1-1 and Ctrl-Md, when exported as json I get the correct tokens

When I export as colnll2003 it seems to apply some form of word tokenization so it creates a single token "AHU-G1-V-1-1-Ctrl-Md -X- _ B-Equip"

I'm not sure if this is a label-studio issue, but prodigy for example applies tokenization before annotation to ensure that the start / end of the selection is align with a token.

**Comment by makseq** [comment]
@david-waterworth can you provide correct and incorrect examples for one entity?

**Comment by david-waterworth** [comment]
@makseq 

This is the "correct" output as json

```
  {
    "completions": [
      {
        "created_at": 1604303915,
        "id": 32001,
        "lead_time": 8.224,
        "result": [
          {
            "from_name": "label",
            "id": "mqjil7Iq1m",
            "to_name": "text",
            "type": "labels",
            "value": {
              "end": 12,
              "labels": [
                "Equip"
              ],
              "start": 0,
              "text": "AHU-G1-V-1-1"
            }
          },
          {
            "from_name": "label",
            "id": "937NmbLsRD",
            "to_name": "text",
            "type": "labels",
            "value": {
              "end": 20,
              "labels": [
                "Point"
              ],
              "start": 13,
              "text": "Ctrl-Md"
            }
          }
        ]
      }
    ],
    "data": {
      "text": "AHU-G1-V-1-1-Ctrl-Md"
    },
    "id": 32
  }
```

This is the same example in CoNLL 2003

`AHU-G1-V-1-1-Ctrl-Md -X- _ B-Equip`

I'm not sure if CoNLL 2003 only applies to text which can be split into "words" by whitespace? I'm not sure how useful that is if you're using some sort of workpiece tokenizer, or like in my case custom tokenization.

i.e. tokenization might get tokenised into "token" "ization/<w>" so the model needs

token -X- _ B
ization/<w> -X- _ I

(i.e. in general I'm not sure how you can map from character spans to BIO encoding without taking into account the tokenizer?)

**Comment by niklub** [comment]
Hi, @david-waterworth !

Indeed, currently, only primitive tokenization is used (by splitting into tokens using whitespaces).
However, I think it could be extended for the custom tokenization scheme, take a look at this https://github.com/heartexlabs/label-studio-converter/blob/master/label_studio_converter/utils.py#L20

Do you think that something like replacing `text.split()` -> `text.split('-')` would solve your problem ?

**Comment by david-waterworth** [comment]
Hi @niklub 

I think it would be close but not correct, the problem is the '-' character is both a delimiter and an infix character in the tagged entities. text.split('-') removes it. I think you may account for that, as you don't tag with 'O' if the next tokens is an 'I'? But my pre-tokeniser splits between characters based on whether the preceding and next are from the same class (char, numeric and punctuation). Then I used the BPE tokeniser which may further split (particularly longer strings) to avoid <UNK> tokens.

I think my best option is to use the json export for now. Long term, being able to pass tokens as inputs to the annotation UI may help i.e. 

{
  "text": {"AHU-G1-V-1-1-Ctrl-Md"},
  "tokens: [{text": "AHU", start=0, end=2}, ...]
}
