### ISSUE TITLE
Export issue Pascal voc xml 

### ISSUE THREAD

**Issue by sumitctm** [heartexlabs/label-studio-converter#166]
Hello,

I'm facing some issue with Export format type Pascal VOC Xml as the same is disable in the export window. Please let me know how to enable this option in Label studio.

![image](https://user-images.githubusercontent.com/73328631/204513552-852182cc-ef1d-4746-8153-57126d9a7b1c.png)

**Comment by saskra** [comment]
I would also like to export my polygon masks in this format, but it is also grayed out, even though polygons are explicitly mentioned in the description.

**Comment by makseq** [comment]
It's not supported, but you can contribute - https://github.com/heartexlabs/label-studio-converter/blob/master/label_studio_converter/converter.py#L914
