### ISSUE TITLE
How can i convert binary mask to RLE format for brushing tool input.

### ISSUE THREAD

**Issue by faizan170** [heartexlabs/label-studio-converter#17]
I have tried to work with some rle converters to convert binary mask to RLE format, but on input, it throws error.
`RangeError: Array buffer allocation failed`
Here is some output from RLE array.
`199501, 1, 996, 7, 992, 9, 991, 9, 991, 10, 990`

Can we use this converter for encoding?
              
[https://github.com/thi-ng/umbrella/blob/develop/packages/rle-pack/src/index.ts](https://github.com/thi-ng/umbrella/blob/develop/packages/rle-pack/src/index.ts)

**Comment by hlomzik** [comment]
Hmm, we are using exact this library. How is your result's value looks like? Like this?
```
{
  format: "rle",
  rle: [199501, 1, 996, 7, 992, 9, 991, 9, 991, 10, 990],
}
```

**Comment by faizan170** [comment]
Yes, I get values like this when convert binary image to rle.
But as i seen on labelstudio output, value does not exceeds 255. They are like this.
`{
  format: "rle",
  rle: [199501, 1, 996, 7, 992, 9, 991, 9, 991, 10, 990],
}`
So, is there any option that i can use python to convert masks, so that i can use as input to labeling tool?

**Comment by bram2506** [comment]
@faizan170 Made a pull request which can cope with colored images. So you can convert your binary image to a colored image using cv2 and use the rle encoding!

**Comment by makseq** [comment]
https://github.com/heartexlabs/label-studio-converter/pull/25

**Comment by makseq** [comment]
Code for brush import from predictions is here: 
https://github.com/heartexlabs/label-studio-converter/pull/25/files#diff-b82fa6eac244e4e2cbee0b3ba3e9582bd74edab647fb9570b1c9ef0f23b7ea4cR172
