### ISSUE TITLE
How to add filter on export the project

### ISSUE THREAD

**Issue by AimannKhan** [heartexlabs/label-studio-converter#181]
I want to download separate files of JSON for each Labeled file, moreover also want to download the Labeled text file, how should it do on LS?

**Comment by makseq** [comment]
Sorry, your question is unclear. 
1. why are you talking about "filter on export" in the title?
2. what are "separate files of JSON for each Labeled file"? 

It's better to show how your export JSON looks like.

**Comment by AimannKhan** [comment]
Hi, Thank you for your response
I want to export each txt file json, by this I need to create different
projects. I need to put multiple text files in one project and then add a
filter that exports individual json for each text file. Is it possible?
 it is a requirement that's why I ask that question I tried and searched
but it is not done

**Comment by makseq** [comment]
The first option is to use easy export API call 
https://labelstud.io/sdk/project.html#label_studio_sdk.project.Project.export_tasks 
you can specify task ids there. 

The second option is to use export snapshots API, where you can pass tab id and tasks from this tab will be taken for the export: 
https://github.com/heartexlabs/label-studio-sdk/blob/72c6279ea494674e7db1d83e599106d4c5c2dafb/examples/export_snapshots.py#L30
In the DM tab you can setup filters as you want to make a task slice.

**Comment by AimannKhan** [comment]
Thank you!
