### ISSUE TITLE
argument config in the constructor of class "Converter"

### ISSUE THREAD

**Issue by Himbeersternchen** [heartexlabs/label-studio-converter#187]
Hi dear contributers,

I am using this great tool label-studio-converter in python. And I checked the example in README. But there is an error, if I call
`c = Converter(<path_name>)`, then the argument "config" in __init__() of class Converter is missing. 

When should I feed this argument "config" into __init__()? And how should this "config" looks like? 

Best Regards

**Comment by Himbeersternchen** [comment]
Hi, 

I have looked into the method Converter.convert_to_json(), and there is nothing about xml to json...It is a method, which is called for json to json.. I didn't get it, how can I do xml2json for label-studio?

Best Regards

**Comment by makseq** [comment]
I've added a docstring to the Converter __init__(). Hope it will clarify. 
https://github.com/heartexlabs/label-studio-converter/blob/master/label_studio_converter/converter.py#L138

It's just the LS labeling config from Project settings / Interface page.

**Comment by Himbeersternchen** [comment]
I 've tried to set the path to xml file as config, but after the usesage of python code in README, i have only got a empty list in the json file. As i said, Converter.convert_to_json() does not convert xml to json, it does convert json to json. I didnt figure out, how can i use this package to convert xml to json..

**Comment by makseq** [comment]
What xml do you mean? LS converter can have json as input only in most cases.
