### ISSUE TITLE
COCO format export gives invalid relative path to image

### ISSUE THREAD

**Issue by 35grain** [heartexlabs/label-studio-converter#188]
For example, an image is stored under `https://localhost/data/upload/1/942a5a02-1669376624.208194.jpg` in Label Studio. The expected file_name in `result.json` is `images/942a5a02-1669376624.208194.jpg` as all images in the export are stored under `images/`, however the `/1` subdirectory is still there: `images/1/942a5a02-1669376624.208194.jpg`.

**Comment by 35grain** [comment]
Noticed there already is another issue on this https://github.com/heartexlabs/label-studio-converter/issues/139

**Comment by makseq** [comment]
@35grain Could you please check the latest master of label-studio-converter, this issue should be fixed there. 
https://github.com/heartexlabs/label-studio-converter/commit/7598b56db403aafa7c88767af388941bb8281347
