### ISSUE TITLE
Cant use '?' and '=' characterers in --image-root-url args

### ISSUE THREAD

**Issue by javi-desp** [heartexlabs/label-studio-converter#193]
When adding this characterers the code transform it to hexadecimal, and I am not able to write the next adress:

/data/local-files?d=images

**Comment by makseq** [comment]
Could you switch to this branch and check how it works please?
https://github.com/heartexlabs/label-studio-converter/pull/195

**Comment by javi-desp** [comment]
nope, with this input : label-studio-converter import yolo --out-type="predictions" --image-root-url '/data/local-files/?d=images' -i ./ -o prelabeling_yolo.json

writes the next: 

[{"data": {"image": "/data/local-files/%3Fd%3Dimages/1675237968.9161572.jpg"}, "predictions": ..... 

when it should be : 


[{"data": {"image": "/data/local-files/?d=images/1675237968.9161572.jpg"}, "predictions": .....

**Comment by makseq** [comment]
@javi-desp I would guess you haven't installed label-studio-converter properly, have you tried to call 
```
git clone .......
git checkout <branh-name>
cd label-studio-converter 
pip install -U -e .
```
