### ISSUE TITLE
YOLO Segmentation

### ISSUE THREAD

**Issue by OpNoob** [heartexlabs/label-studio-converter#208]
Is there a yolo segmentation output format?  I am using yolov5 segmentation, and since I am using the polygons, the export is not enabled for me.

**Comment by makseq** [comment]
Yes, it should be available in the latest develop branch of LS.

**Comment by patcharees** [comment]
@makseq How about import ?

I am using latest version 0.0.54. It does not support import yolo segmentation.

**Comment by OpNoob** [comment]
> Yes, it should be available in the latest develop branch of LS.

Hi, yes YOLO polygon annotation is supported in the latest version. Thanks for the help :)
