### ISSUE TITLE
Can't Export VOC Image Segmentation

### ISSUE THREAD

**Issue by stevebit** [heartexlabs/label-studio-converter#24]
Hi, 
I'm getting the following error "FileNotFoundError: [Error 2] No such file or directory" when I try to export the labelled images using the VOC format.

**Comment by makseq** [comment]
@stevebit Thank you for your report, there is duplicated issue: https://github.com/heartexlabs/label-studio/issues/627#issuecomment-793517595 , but we haven't yet fixed it.
