### ISSUE TITLE
COCO export error

### ISSUE THREAD

**Issue by rm-data-viz** [heartexlabs/label-studio-converter#30]
Hi,

I'm getting the following error on exporting COCO format in label studio and I believe that label-studio-converters is the reason for this error.

`FileNotFoundError("Can't find upload dir: either LS_UPLOAD_DIR or project should be passed to converter")`
`FileNotFoundError: Can't find upload dir: either LS_UPLOAD_DIR or project should be passed to converter`

Actually, I fixed it by adding 

`upload_dir=self.upload_dir` as a parameter in download function for convert_to_coco.

Please correct me if this issue is already opened because I couldn't find one in Issues. 

Thanks!

**Comment by makseq** [comment]
Could you show LS and LS-converter version you are using?

**Comment by mehrarahul** [comment]
Im using the below docker version of LS.

`docker run -it -p 8080:8080 -v `pwd`/mydata:/label-studio/data heartexlabs/label-studio:latest`

**Comment by dallidalli** [comment]
I'm having the same issue. Pascal VOC export is working fine, COCO gives me above error.

According to `pip freeze`, these are the used versions:

`label-studio==1.0.0.post3
label-studio-converter==0.0.26`

I installed it under Windows, Python 3.8 using `pip install -U label-studio`.

**Comment by makseq** [comment]
@dallidalli Could you try release/1.0.1 branch? 
https://github.com/heartexlabs/label-studio/pull/681

**Comment by dallidalli** [comment]
@makseq I tried to do so, but maybe it wasn't the right way. I tried the following:
- uninstall the current label-studio installation via `pip uninstall label-studio`
- install the mentioned branch using `pip install git+https://github.com/heartexlabs/label-studio.git@release/1.0.1`

The issue still persists, plus label-studio doesn't look so neat anymore, so I guess I did something wrong when trying the mentioned branch.

Anyways here is a more complete Traceback:


```
Traceback (most recent call last):
  File "c:\users\dalli\desktop\python_labelling\venv\lib\site-packages\label_studio_converter\converter.py", line 374, in convert_to_coco
    image_path = download(image_path, output_image_dir, project_dir=self.project_dir, return_relative_path=True)
  File "c:\users\dalli\desktop\python_labelling\venv\lib\site-packages\label_studio_converter\utils.py", line 95, in download
    upload_dir = _get_upload_dir(project_dir, upload_dir)
  File "c:\users\dalli\desktop\python_labelling\venv\lib\site-packages\label_studio_converter\utils.py", line 86, in _get_upload_dir
    raise FileNotFoundError("Can't find upload dir: either LS_UPLOAD_DIR or project should be passed to converter")
FileNotFoundError: Can't find upload dir: either LS_UPLOAD_DIR or project should be passed to converter
```

**Comment by makseq** [comment]
@dallidalli Could you please clone and install label-studio-converter from the master branch and check - is it working for you now? 
https://github.com/heartexlabs/label-studio-converter

**Comment by makseq** [comment]
>  (Except (of course) for the warning during installation regarding an incompatible label-studio-converter version, as label-studio requires 0.0.26)

It's not a problem :slightly_smiling_face: 

Thank you very much for your help! I hope we can close this issue. Feel free to reopen if you have these problems again.
