### ISSUE TITLE
YOLO Labeling Format

### ISSUE THREAD

**Issue by men1n2** [heartexlabs/label-studio-converter#33]
Hello,

 It will be nice to have the option to export the annotations directly to the YOLO txt format when doing Object Detection with Bounding Boxes projects without having to export to another format than using external script to do the conversion.

I would like to hear from you if this feature can/will be implemented ? And thanks

**Comment by makseq** [comment]
@men1n2 
Yes! We have an implementation of it already (great thanks to @johnson7788).
But we haven't released it yet. 

You can check it out from master branch:

```
# ... activate your python env for Label Studio ...
git clone https://github.com/heartexlabs/label-studio-converter.git
cd label-studio-converter
pip install -e .
```

Go to project Export, try YOLO.

**Comment by men1n2** [comment]
@makseq Thanks for your quick reply. It is nice to see that the feature is already implemented :)
