### ISSUE TITLE
license mismatch readme vs setup.py

### ISSUE THREAD

**Issue by dehesselle** [heartexlabs/label-studio-converter#35]
Hello,
the readme says Apache-2.0 but setup.py says MIT - which one is it?

**Comment by makseq** [comment]
@dehesselle The correct one is Apache 2.0. 
Thank you for your report. 

Fixed in https://github.com/heartexlabs/label-studio-converter/commit/9ef1c8ab946df42c65bb148c8c08f2695110c4da#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7
