### ISSUE TITLE
Please update new README file？

### ISSUE THREAD

**Issue by gherao** [heartexlabs/label-studio-converter#36]
Thanks for the conversion tool!
When i use now source to convert my data export from label-studio,next error has occured.
```
converter/label_studio_converter/sample.py", line 3, in <module>
    c = Converter('/Users/gaohe/Downloads/config.xml')
TypeError: __init__() missing 1 required positional argument: 'project_dir'
```

Can you update the Readme file on how to use it.
The converter parameters like config. xml are what file？
the project_dir is the path to what.
How do I set these parameters if I am starting from docker?
Thanks

**Comment by mattkanwisher** [comment]
think the config.xml are in their main repo, I was a bit confused at first also https://github.com/heartexlabs/label-studio/tree/61d883810eacabedfd0248eb3d851763924f07be/label_studio/examples

**Comment by gherao** [comment]
@mattkanwisher Thanks for your reply, it helped me a lot!!!
