### ISSUE TITLE
yolo preannotated dataset

### ISSUE THREAD

**Issue by haviduck** [heartexlabs/label-studio-converter#45]
Hey, we are moving our operation to label studio from cvat. we have a bunch of pre-annotated images that exist in yolos 1 txt file per image thing. Do you know a way i can batch convert these to label studio's json format?

**Comment by makseq** [comment]
Hi, check this PR please: https://github.com/heartexlabs/label-studio-converter/pull/46

**Comment by makseq** [comment]
@smoreface I've added YOLO => LS Json format converter (see https://github.com/heartexlabs/label-studio-converter/pull/46). 
I would like to add this into our docs, what do you think about it?

**Comment by haviduck** [comment]
> Hi, check this PR please: #46

absolutely spot on. i -really- dig label studio and this removes the last block for integration for me. thank you thank you thank you. Now to nag about ml backend integration :)

**Comment by makseq** [comment]
@haviduck This is yolo structure. 
I've updated codes, please, pull the latest changes.
1. Now categories are taken from classes.txt (instead of notes.json).
2. Labeling config for the project will be generated automatically. 

```
images
 - 1.jpg
 - 2.jpg
 - ...
labels
 - 1.txt
 - 2.txt

classes.txt
```

classes.txt example
```
Airplane
Car
```

**Comment by haviduck** [comment]
> @haviduck This is yolo structure.
> I've updated codes, please, pull the latest changes.
> 
> 1. Now categories are taken from classes.txt (instead of notes.json).
> 2. Labeling config for the project will be generated automatically.
> 
> YOLO export example:
> 
> ```
> images
>  - 1.jpg
>  - 2.jpg
>  - ...
> labels
>  - 1.txt
>  - 2.txt
> 
> classes.txt
> ```
> 
> classes.txt example
> 
> ```
> Airplane
> Car
> ```

perfect,  thank you! im seeing some discrepancies, but i will do more research, before making a claim. thanks for swift and good support.

**Comment by makseq** [comment]
@haviduck Waiting for your feedback and details :)

**Comment by haviduck** [comment]
issue was with my own shitty pseudolabeling :) works great, thanks a bunch!

**Comment by haviduck** [comment]
im not gonna complain about open source stuff, but some quick feedback, adding local storage along with a labelstudio json file isnt super intuitive. i found myself mounting my images then connecting them via the storace connector. the image url had  a ?d paramater that my converted json didnt honor. its just a matter of search and replace, but it was a bit unclear until then. i couldnt sync the mount AND upload the json as it would duplicate tasks. id be more than happy to push a pr or help out if needed, just some feedback.

**Comment by makseq** [comment]
@haviduck PRs are highly appreciated!
