### ISSUE TITLE
Pull request: In the readme please fix the convert_to_csv

### ISSUE THREAD

**Issue by thenamangoyal** [heartexlabs/label-studio-converter#6]
Hi 

The convert_to_csv example in main readme should be
`c.convert_to_csv('examples/sentiment_analysis/completions/', 'tmp', sep='\t', header=True)`

basically output destination is directory e.g. 'tmp' not a file

instead of current
`c.convert_to_csv('examples/sentiment_analysis/completions/', 'tmp/output.tsv', sep='\t', header=True)`

**Comment by niklub** [comment]
Thanks, that's fixed!
