### ISSUE TITLE
show unicode more user-friendly in exported csv files

### ISSUE THREAD

**Issue by loveychen** [heartexlabs/label-studio-converter#64]
https://github.com/heartexlabs/label-studio-converter/blob/a4498f8b352196dd91035bdbc75de5848fa1c528/label_studio_converter/converter.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L384

When exporting project to a csv file, it shows multiple-choices in unicode format  (like `\uxxxx`), and it is not user friendly.

I am thinking if we can add `ensure_ascii=False` option to `json.dumps()`, and the final code comes like 

```python
for name, value in item['output'].items():
        pretty_value = self._prettify(value)
        record[name] = pretty_value if isinstance(pretty_value, str) else json.dumps(pretty_value, ensure_ascii=False)
```

**Comment by makseq** [comment]
@loveychen Could you create a PR please?

**Comment by loveychen** [comment]
> @loveychen Could you create a PR please?

@makseq sorry for replying later. I have created a PR https://github.com/heartexlabs/label-studio-converter/pull/65
