### ISSUE TITLE
Issue on the test image file

### ISSUE THREAD

**Issue by karamusluk** [heartexlabs/label-studio-converter#67]
Hi all,
Once I checked test file is corrupted.
https://github.com/heartexlabs/label-studio-converter/blob/19316e876c01e066b8584b72b0b072497f3afcfb/tests/test.png

I coudln't understand how the things work while using image2annotation.

Could you please clarify what type of image should be supplied to this function?

**Comment by makseq** [comment]
@karamusluk Hi, thank you for your report. I've fixed this image, please check it again in the latest master commits. 
Also I've updated descriptions - https://github.com/heartexlabs/label-studio-converter/blob/master/label_studio_converter/brush.py#L366 - hope now they are a little bit clearer.
