### ISSUE TITLE
Allow multiple completions export for CONLL2003

### ISSUE THREAD

**Issue by RasmusEdvardsen** [heartexlabs/label-studio-converter#8]
Hey, I made a PR for allowing multiple completions in an export when exporting CONLL2003 format.
It takes the latest added unskipped completion, or None if none exist.
Of course I don't know if this is the desired behavior, so let me know what you think.

#7

**Comment by RasmusEdvardsen** [comment]
@makseq do you also maintain this repo?

**Comment by makseq** [comment]
@RasmusEdvardsen yes. I will investigate you PR and merge to release 0.7.4 if it is ok.

**Comment by RasmusEdvardsen** [comment]
Sounds lovely @makseq , and yea well, it's an extremely useful tool for us, so the thanks should be to you guys 😊
