### ISSUE TITLE
Interpretation of RLE values

### ISSUE THREAD

**Issue by TeodorChiaburu** [heartexlabs/label-studio-converter#95]
Hello! 

May I ask what the **RLE** values stored for brush segmentations stand for? I am familiar with this encoding method from _COCO_, but I was used to them being understood as **pixel counts**. For instance, an **RLE** vector such as `[234, 54, 103, 3,...]` would mean that the first 234 pixels (counting from the top of the image, from left to right) are not masked, the following 54 are masked, the next 103 not masked, then 3 masked again and so on. But apparently, this is not the meaning that Label Studio is using, right? Is it something more like `[start_pixel_1, num_masked_pixels_1, start_pixel_2, num_masked_pixels_2...]`?

Thank you!

**Comment by makseq** [comment]
@TeodorChiaburu I don't remember the exact implementation, but you will find this info here: https://github.com/heartexlabs/label-studio-converter/blob/master/label_studio_converter/brush.py

Also this would be helpful: 
https://labelstud.io/guide/predictions.html#Import-brush-segmentation-pre-annotations-in-RLE-format

**Comment by pinecho** [comment]
@makseq 
Hello, I have the same question.
the `test_rle_encoding` in `tests/test_brush.py` showed that the rle encoding in Label Studio did not reduce the occupied space(the rle_test is longer and larger than test_arr, isn't it?).
Could you please give some detail about the rle format in Label Studio?
Thank you.
```
def test_rle_encoding():
    """testing rle encoding with simple example"""
    test_arr = [1, 1, 1, 1, 2, 3, 5, 6, 7, 8, 4, 4, 4, 4, 4, 4, 4, 4]
    rle_test = encode_rle(test_arr)
    assert rle_test == [0, 0, 0, 18, 57, 27, 252, 96, 32, 1, 0, 6, 0, 40, 0,
                        192, 3, 128, 17, 56, 32]
```

**Comment by makseq** [comment]
As I remember pixels will be encoded as 4 color-values, so this example is not indicative. Better to use something like `[1,1,1,1,  2,2,2,2,  5,5,5,5,  7,7,7,7]`

**Comment by sandeepgoshika** [comment]
I want to decode RLE to image. Is there any code form label-studio.

**Comment by makseq** [comment]
Check this:
https://github.com/heartexlabs/label-studio-converter/blob/master/label_studio_converter/brush.py#L144

**Comment by pranavys** [comment]
Hello,
Unique mask values has to be 0,1 but I am getting more than 2 values.
How can I resolve it?

**Comment by makseq** [comment]
Hi, try thresholding it like mask > 128. 
Similar to this: https://labelstud.io/guide/predictions.html#Import-brush-segmentation-pre-annotations-in-RLE-format
