### ISSUE TITLE
YOLO format disabled

### ISSUE THREAD

**Issue by yangboz** [heartexlabs/label-studio-converter#97]
when exporting  in labelStudio , the popup format option with  YOLO format is disabled.

![Screenshot 2022-04-14 at 11 25 16 AM](https://user-images.githubusercontent.com/481954/163307648-5561481b-0d88-4cd4-ac29-39354df05f8c.png)

still WIP?

**Comment by makseq** [comment]
@yangboz It works only for RectangleLabels / Rectangle tags.

**Comment by yangboz** [comment]
> @yangboz It works only for RectangleLabels / Rectangle tags.

but  how ? convert from JSON exported from labelstudio?

**Comment by makseq** [comment]
This option will be available automatically if you use RectangleLabels in your labeling config.

**Comment by yangboz** [comment]
yes, after using RectangleLabels , then try export  button ,take forever time, any idea?

thanks.

**Comment by makseq** [comment]
how many tasks do you have in your project?

**Comment by yangboz** [comment]
> how many tasks do you have in your project?

more over 100 tasks , the more times of  exporting will taken.

**Comment by makseq** [comment]
Sorry for the long answer. Do you still have this issue with the long export? Could you check the LS media directory 
![image](https://user-images.githubusercontent.com/501780/165646929-e545cc58-829f-42d8-b580-df4f8e6c1212.png)

It should store the export file in `export` subfolder.
